In [3]:
import torch
torch.__version__

'2.1.2+cu118'

In [4]:
import numpy as np
np.__version__

'1.24.1'

In [5]:
torch.cuda.is_available()

True

In [6]:
torch.cuda.device_count()

1

In [7]:
torch.cuda.current_device()

0

In [8]:
torch.cuda.memory_allocated()

0

In [9]:
torch.cuda.memory_reserved()

0

In [10]:
# create a tensor
# scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [11]:
scalar.ndim

0

In [12]:
scalar.item()

8

In [13]:
# vector
vec = torch.tensor([4, 3])
vec

tensor([4, 3])

In [14]:
vec.shape

torch.Size([2])

In [15]:
vec.ndim

1

In [16]:
# matrix
mat = torch.tensor([
    [1, 2, 3],
    [2, 0, -3]
])

mat

tensor([[ 1,  2,  3],
        [ 2,  0, -3]])

In [17]:
mat.device

device(type='cpu')

In [18]:
mat.shape

torch.Size([2, 3])

In [19]:
mat.ndim

2

In [20]:
mat[0]

tensor([1, 2, 3])

In [21]:
mat[1]

tensor([ 2,  0, -3])

In [22]:
mat[:, 1]

tensor([2, 0])

In [23]:
mat[:, [1, 2]]

tensor([[ 2,  3],
        [ 0, -3]])

In [24]:
mat[:, 1].reshape(-1, 1)

tensor([[2],
        [0]])

In [25]:
mat[:, 1].reshape(-1, 1).shape

torch.Size([2, 1])

In [26]:
# tensor
TENSOR = torch.tensor([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [27]:
TENSOR.device

device(type='cpu')

In [28]:
TENSOR.shape

torch.Size([1, 3, 3])

In [29]:
TENSOR.ndim

3

In [30]:
help(torch.rand)

Help on built-in function rand in module torch:

rand(...)
    rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor
    
    Returns a tensor filled with random numbers from a uniform distribution
    on the interval :math:`[0, 1)`
    
    The shape of the tensor is defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
    
    Keyword args:
        generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, option

In [31]:
# create random tensor in Pytorch

MAT = torch.rand((4, 4))
MAT

tensor([[0.3880, 0.1261, 0.1628, 0.9813],
        [0.6461, 0.5598, 0.8576, 0.6910],
        [0.0598, 0.1820, 0.1476, 0.3303],
        [0.7738, 0.8200, 0.0750, 0.5458]])

In [32]:
torch.rand(1, 4)

tensor([[0.1711, 0.5612, 0.0069, 0.5656]])

In [33]:
random_image = torch.rand(size=(3, 32, 32)) # (channel, height, width)
random_image.shape

torch.Size([3, 32, 32])

In [34]:
random_image.device

device(type='cpu')

In [35]:
row0 = random_image[1, :, 0]

In [36]:
col1 = random_image[1, 1, :]

In [37]:
row0.shape[0]

32

In [38]:
row0 = row0.reshape(row0.shape[0], -1)

In [39]:
col1 = col1.reshape(-1, col1.shape[0])

In [40]:
col1

tensor([[6.1488e-01, 7.6949e-01, 9.7954e-01, 4.5205e-01, 8.6972e-01, 3.0517e-01,
         1.7498e-01, 5.0674e-01, 9.3933e-01, 6.6015e-01, 4.8473e-01, 6.8884e-01,
         8.2439e-02, 3.3409e-01, 9.5526e-01, 7.8673e-01, 1.4298e-01, 8.5307e-01,
         4.9277e-01, 7.3417e-03, 8.8592e-01, 4.0535e-01, 5.7756e-01, 3.9052e-01,
         4.1086e-01, 2.0647e-01, 2.9433e-01, 1.1214e-02, 8.3061e-01, 3.6524e-01,
         6.4594e-04, 5.6831e-01]])

In [41]:
row0.shape, col1.shape

(torch.Size([32, 1]), torch.Size([1, 32]))

In [42]:
row0.ndim, col1.ndim

(2, 2)

In [43]:
res = row0 @ col1
res.shape

torch.Size([32, 32])

In [44]:
row0_transpose = row0.t()
col1_transpose = col1.t()

In [45]:
torch.matmul(row0_transpose, col1_transpose)

tensor([[8.9258]])

In [46]:
row0.T

tensor([[0.2503, 0.6149, 0.9254, 0.8662, 0.2094, 0.5469, 0.8762, 0.4878, 0.4134,
         0.7117, 0.7920, 0.5796, 0.0329, 0.8300, 0.8984, 0.0999, 0.4926, 0.9854,
         0.9332, 0.7033, 0.1313, 0.9549, 0.3091, 0.1678, 0.8310, 0.8817, 0.8335,
         0.6883, 0.4806, 0.2188, 0.8295, 0.0236]])

In [47]:
torch.matmul(row0.T, col1.T)

tensor([[8.9258]])

* The `torch.dot()` function is used to compute the dot product of two `1-dimensional tensors (vectors)`. 
It only works for `1D tensors (vectors)` of the same length and returns a scalar value as the result. If you want to perform dot product or matrix multiplication on higher-dimensional tensors, you should use other functions like `torch.matmul()` or `torch.mm()`.

In [48]:
torch.dot(row0.T, col1.T)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [49]:
torch.mm(row0.T, col1.T)

tensor([[8.9258]])

In [50]:
M = torch.arange(start=0, end=10, step=1).reshape(-1, 5)
M

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [51]:
M.min(axis=1)

torch.return_types.min(
values=tensor([0, 5]),
indices=tensor([0, 0]))

In [52]:
type(M.min(axis=1))

torch.return_types.min

In [53]:
M.min(axis=1).values

tensor([0, 5])

In [54]:
M.min(axis=1).indices

tensor([0, 0])

In [55]:
M.max(axis=0)

torch.return_types.max(
values=tensor([5, 6, 7, 8, 9]),
indices=tensor([1, 1, 1, 1, 1]))

In [93]:
M.sum(axis=0)

tensor([ 5,  7,  9, 11, 13])

In [94]:
M.sum(axis=1)

tensor([10, 35])

In [99]:
torch.min(M), torch.sum(M), torch.mean(M.float())

(tensor(0), tensor(45), tensor(4.5000))

In [102]:
M.float().mean(axis=0)

tensor([2.5000, 3.5000, 4.5000, 5.5000, 6.5000])

In [105]:
torch.argmin(M, axis=0), torch.argmin(M, axis=1)

(tensor([0, 0, 0, 0, 0]), tensor([0, 0]))

In [108]:
M

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [107]:
torch.argmax(M, axis=1), torch.argmax(M, axis=0)

(tensor([4, 4]), tensor([1, 1, 1, 1, 1]))

In [110]:
help(torch.randn)

Help on built-in function randn in module torch:

randn(...)
    randn(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor
    
    
    Returns a tensor filled with random numbers from a normal distribution
    with mean `0` and variance `1` (also called the standard normal
    distribution).
    
    .. math::
        \text{out}_{i} \sim \mathcal{N}(0, 1)
    
    The shape of the tensor is defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
    
    Keyword args:
        generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: i

In [109]:
A = torch.randn(size=(2, 5))
A

tensor([[-0.6840,  1.0695, -0.2650,  0.2678, -0.3110],
        [ 1.2860,  0.6443, -1.1738, -0.0997,  1.0986]])

In [111]:
torch.argmin(A, axis=0)

tensor([0, 1, 1, 1, 0])

In [112]:
torch.argmin(A, axis=1)

tensor([0, 2])

In [113]:
## reshaping, stacking, squeezing and unsqueezing tensors
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [115]:
torch.reshape(x, (3, 3))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [124]:
# ones vec
ones_vec = torch.ones((10))
ones_vec = ones_vec.reshape(10, -1)
ones_vec.shape

torch.Size([10, 1])

In [122]:
X = torch.randn(size=(10, 3))
X.shape

torch.Size([10, 3])

In [127]:
data = torch.hstack((ones_vec, X))
data.shape

torch.Size([10, 4])

In [128]:
data.T

tensor([[ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,
          1.0000,  1.0000],
        [ 1.8016,  1.7513, -0.7202, -0.0782, -0.7815,  1.6377,  1.4631,  1.3267,
         -1.2239,  1.6972],
        [-0.9753,  0.4215,  1.7771,  2.7243,  2.1704,  0.1959,  1.8536, -1.2474,
          0.9036,  0.0300],
        [ 1.5669, -1.9226,  0.1031, -2.5455, -0.3547, -0.1787,  2.1079, -0.2167,
         -0.7478,  1.0386]])

In [134]:
a = torch.zeros_like(torch.tensor([1, 2, 3]))
a

tensor([0, 0, 0])

In [141]:
a = torch.zeros((10))
a = a.reshape(-1, 10)
a

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [145]:
a.shape

torch.Size([1, 10])

In [143]:
Y = torch.randn((4, 10))
Y.shape

torch.Size([4, 10])

In [144]:
Y

tensor([[ 1.0367, -0.8410, -0.9029,  0.3080,  0.7225,  0.1679,  1.4663, -1.4606,
          2.4284, -0.2118],
        [ 0.3742,  0.4999,  0.2300,  1.5903, -1.8920, -1.7578,  1.1470, -0.1886,
          0.3001, -0.7935],
        [ 0.2670, -0.2104,  1.2138,  0.3096, -1.3950,  0.3993,  0.7628,  0.9263,
          2.0496, -0.1135],
        [-1.2078, -2.2362, -0.8972, -1.1744, -0.8349, -0.2917, -1.2816,  1.7956,
         -0.1776, -0.6973]])

In [153]:
V = torch.vstack((Y, a))
V.shape

torch.Size([5, 10])

In [149]:
c = torch.squeeze(a)
c

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [150]:
torch.squeeze(c)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [154]:
V_after = torch.squeeze(V)
V_after.shape

torch.Size([5, 10])

In [156]:
v = torch.tensor([[1.0]])
w = torch.squeeze(v)
w

tensor(1.)

In [157]:
u = torch.rand((5, 1))
u

tensor([[0.6254],
        [0.0154],
        [0.1685],
        [0.8914],
        [0.4866]])

In [160]:
w = torch.squeeze(u)
torch.unsqueeze(w, dim=1)

tensor([[0.6254],
        [0.0154],
        [0.1685],
        [0.8914],
        [0.4866]])

In [162]:
torch.unsqueeze(w, dim=0)

tensor([[0.6254, 0.0154, 0.1685, 0.8914, 0.4866]])

In [56]:
# tensor from numpy
arr = np.random.rand((10))
arr

array([0.01156145, 0.16281464, 0.67989322, 0.32470471, 0.66775688,
       0.95144361, 0.945082  , 0.90166446, 0.40864752, 0.18564053])

In [57]:
t = torch.from_numpy(arr)
t

tensor([0.0116, 0.1628, 0.6799, 0.3247, 0.6678, 0.9514, 0.9451, 0.9017, 0.4086,
        0.1856], dtype=torch.float64)

##### Matrix Multiplication

In [ ]:
# getting tensor to run on GPU

In [93]:
import time

In [94]:
P = torch.randn((5, 2), device="cuda")
P

tensor([[ 1.1419,  0.4717],
        [ 1.2772,  1.2758],
        [-0.2071,  0.6053],
        [ 1.5214, -1.0856],
        [-0.0436,  1.1371]], device='cuda:0')

In [95]:
Q = torch.rand((2, 5), device="cuda")
Q

tensor([[0.6944, 0.6031, 0.4045, 0.9086, 0.0177],
        [0.0625, 0.0038, 0.7694, 0.2538, 0.4959]], device='cuda:0')

In [96]:
%%time

R = torch.mm(P, Q)
R.shape

CPU times: total: 0 ns
Wall time: 0 ns


torch.Size([5, 5])

In [97]:
R

tensor([[ 0.8224,  0.6905,  0.8249,  1.1572,  0.2541],
        [ 0.9666,  0.7751,  1.4983,  1.4842,  0.6553],
        [-0.1060, -0.1226,  0.3820, -0.0345,  0.2965],
        [ 0.9885,  0.9134, -0.2199,  1.1067, -0.5115],
        [ 0.0408, -0.0220,  0.8573,  0.2490,  0.5632]], device='cuda:0')

In [98]:
W = torch.randn((5, 2), device="cpu")
W

tensor([[ 0.9458, -0.8641],
        [ 1.1907,  0.3650],
        [ 0.3415, -0.9189],
        [ 1.1267, -1.6895],
        [ 1.1092, -0.5340]])

In [99]:
U = torch.rand((2, 5), device="cpu")
U

tensor([[0.6965, 0.9392, 0.1713, 0.6945, 0.0548],
        [0.3260, 0.0605, 0.1531, 0.0294, 0.7518]])

In [100]:
%%time

V = torch.mm(W, U)
V.shape

CPU times: total: 0 ns
Wall time: 125 µs


torch.Size([5, 5])

In [78]:
%%time

Z = torch.mm(R, V)
Z.shape

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

In [101]:
torch.cuda.memory_allocated()

8524288

In [82]:
torch.mm(R.to("cpu"), V)

tensor([[ 1.3370,  2.0454,  0.5695,  1.1223,  1.4251],
        [ 1.0348,  1.3561, -0.2067, -0.1744,  0.4013],
        [ 0.6506,  1.0330,  0.3848,  0.7195,  0.8101],
        [ 0.1476,  0.1819, -0.0623, -0.0777,  0.0217],
        [ 0.1862,  0.3975,  0.4004,  0.6736,  0.5465]])

In [83]:
R

tensor([[-6.5369e-01, -1.0781e+00, -3.5343e-01, -5.2894e-01, -1.5423e-01],
        [ 5.2905e-01,  4.3624e-01,  7.1568e-01, -1.1055e-01,  8.8305e-01],
        [-4.9017e-01, -7.3586e-01, -3.3646e-01, -3.0706e-01, -2.4172e-01],
        [ 1.2786e-01,  1.2657e-01,  1.5215e-01, -6.2549e-04,  1.7669e-01],
        [-6.0431e-01, -7.8030e-01, -5.3979e-01, -2.2187e-01, -5.1859e-01]],
       device='cuda:0')

In [84]:
R.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [86]:
R.cpu().numpy()

array([[-6.5368694e-01, -1.0780874e+00, -3.5342708e-01, -5.2893782e-01,
        -1.5422565e-01],
       [ 5.2905166e-01,  4.3624246e-01,  7.1567833e-01, -1.1054772e-01,
         8.8304991e-01],
       [-4.9017078e-01, -7.3586488e-01, -3.3645770e-01, -3.0706468e-01,
        -2.4172246e-01],
       [ 1.2786220e-01,  1.2656617e-01,  1.5215452e-01, -6.2548555e-04,
         1.7668797e-01],
       [-6.0431290e-01, -7.8029698e-01, -5.3979307e-01, -2.2187215e-01,
        -5.1858950e-01]], dtype=float32)

In [102]:
# Check the actual allocated memory
allocated_memory = torch.cuda.memory_allocated()
print(f"Memory allocated: {allocated_memory} bytes")

Memory allocated: 8524288 bytes


In [103]:
torch.cuda.memory_reserved()


23068672

In [104]:
del P, Q, R

In [105]:
# Empty the cache to release unused reserved memory
torch.cuda.empty_cache()

In [106]:
# Check the reserved memory after cache is cleared
reserved_memory_after = torch.cuda.memory_reserved()
print(f"Memory reserved after emptying cache: {reserved_memory_after} bytes")

Memory reserved after emptying cache: 23068672 bytes


In [107]:
print(f"Memory allocated: {torch.cuda.memory_allocated()} bytes")

Memory allocated: 8524288 bytes
